#
#  Copyright 2023 Netflix, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
#  the License. You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
#  an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
#  specific language governing permissions and limitations under the License.
#


FROM ubuntu:22.04 AS builder
LABEL maintainer="Netflix OSS <conductor@netflix.com>"

RUN \
    apt-get update && \
    apt-get install -y \
        curl \
        gnupg2 && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        nodejs \
        yarn && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/conductor/ui

COPY ui .

RUN \
    yarn install && \
    yarn build

FROM nginx:1.23
LABEL maintainer="Netflix OSS <conductor@netflix.com>"

WORKDIR /opt/conductor-ui/
COPY --from=builder /tmp/conductor/ui/build /usr/share/nginx/html

VOLUME [ "/etc/nginx/conf.d/default.conf" ]
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD [ "curl", "http://localhost/" ]
