scrape_configs:
  - job_name: 'Conductor Scrapper'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['server:8080']
        labels:
          application: 'Conductor'
