version: "3.9"

services:
  server:
    extends:
      file: docker-compose.base.yaml
      service: server
    volumes:
      - "./config/config.properties:/app/config/config.properties"
    links:
      - elasticsearch
      - redis
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy

  ui:
    extends:
      file: docker-compose.base.yaml
      service: ui
    links:
      - server
    depends_on:
      server:
        condition: service_healthy

  redis:
    extends:
      file: docker-compose.base.yaml
      service: redis

  elasticsearch:
    extends:
      file: docker-compose.base.yaml
      service: elasticsearch

volumes:
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local

networks:
  internal: {}
