version: "3.9"

services:
  server:
    extends:
      file: docker-compose.base.yaml
      service: server
    volumes:
      - "./config/config-postgresql.properties:/app/config/config.properties"
    links:
      - redis
      - postgresql
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy

  ui:
    extends:
      file: docker-compose.base.yaml
      service: ui

  redis:
    extends:
      file: docker-compose.base.yaml
      service: redis

  elasticsearch:
    extends:
      file: docker-compose.base.yaml
      service: elasticsearch

  postgresql:
    extends:
      file: docker-compose.base.yaml
      service: postgresql

volumes:
  elasticsearch-data:
    driver: local
  postgresql-data:
    driver: local
  redis-data:
    driver: local

networks:
  internal: {}
